### ISSUE TITLE
When restart kibana, it shows "Could not locate that index-pattern"

### ISSUE THREAD

**Issue by scf0920** [opendistro/for-elasticsearch-docs#45] opened 2019-04-09 03:20 UTC
Steps to Reproduce:
1. create user "someone"
2. use "someone" login to kibana and create some "index-pattern"
3. restart kibana 
4. use "someone" login to kibana and view "index-pattern", you can see "Could not locate that index-pattern"
![image](https://user-images.githubusercontent.com/16220813/55771149-66b37f80-5ab9-11e9-82fa-bf4939e54e14.png)

**Comment by aetter** [comment] 2019-04-09 17:12
Hi @scf0920, this sounds like a permissions issue. Can you log in as `admin` and check the permissions for `someone` under **Role Mappings**? Then check to make sure those roles have the basic permissions you might need?

**Comment by scf0920** [comment] 2019-04-10 15:47
@aetter  But it works well until  kibana was restarted. And the API returns the correct results.
My security config:
Roles:
![image](https://user-images.githubusercontent.com/16220813/55892185-6a91ef80-5be8-11e9-8880-bdab5c380b1f.png)
Role Map:
![image](https://user-images.githubusercontent.com/16220813/55892241-8bf2db80-5be8-11e9-8473-717ff3aadf05.png)
Users:
![image](https://user-images.githubusercontent.com/16220813/55892331-bb094d00-5be8-11e9-8469-e103198888d9.png)

My solution:
1. export all ```Saved Objects``` as a.json file
2. delete .kibana_*_someone*
3. log back in ```someone```
4. import a.json into ```Saved Objects```

Everything was back to normal...
I think it's kibana security plugin's bug. It's going to reproduce 100%.  Please try to reproduce. 
Thanks.

**Comment by scf0920** [comment] 2019-04-11 02:33
@aetter can you reproduce it?

**Comment by aetter** [comment] 2019-04-11 04:16
Hi @scf0920, unfortunately, no, I can't reproduce your error.

- When I log in with `someone`, I'm unable to create an index pattern, because I can't read any data (as expected).
- When I have the administrator add an index called `someone`, I still can't create an index pattern. (See image.)

<img width="1384" alt="pattern" src="https://user-images.githubusercontent.com/9122297/55930392-d28b0a80-5bd5-11e9-991d-683e6fb7d7c8.png">

- When I map `someone` to `kibana_user`, now I can create the index pattern, but I can't do much else (as expected).
- When I `docker-compose stop` and `docker-compose start` and log in as `someone`, I still have my index pattern.

Can you reproduce from a brand new 0.8.0 cluster? If so, can you post your `docker-compose.yml` and the start to finish steps?

**Comment by scf0920** [comment] 2019-04-12 11:45
@aetter  Very thanks.. I finally found the reason...
Before:
![image](https://user-images.githubusercontent.com/16220813/56034582-3f2f1200-5d5a-11e9-82a5-0e6a9eb14726.png)
After I change:
![image](https://user-images.githubusercontent.com/16220813/56034671-946b2380-5d5a-11e9-8e5a-f53a04a50c9b.png)
Then I log in as ```someone```, my index pattern back to normal...
In a word, ```someone``` has miss index permissions of ```.kibana_137589622_brainpp_2```. But I think it should be automatic...
You can map ```someone``` to my ```own_index``` and see if you can reproduce.

**Comment by aetter** [comment] 2019-04-12 16:15
Hi @scf0920, yeah, I think that's a suggestion worth discussing in a broader forum. I'm closing this issue, but opened https://github.com/opendistro-for-elasticsearch/security/issues/31 so that we can discuss if there are any negative side effects to making this sort of change. Thanks a bunch!

**Closed by aetter** 2019-04-12 16:15 UTC
